// M48 (PLAN_BROWSER_PERF_SECURITY.md §2.20, D82) — k6 counterpart to ../tflw/ticket-write.tflw:
// isolated write rung against `POST /tickets` (a second uncontended write shape, distinct from
// dogfood-post-uncontended.js's cart-add — writes a Ticket + a companion TicketEvent row per
// request), same login-once + retry-on-401 session handling as the rest of the authed rungs.
// `LoadAdminService.reset()` was extended (this milestone) to clean up the load user's tickets
// between runs — reset before each run, same as the other dogfood rungs.
//
// `summaryTrendStats` extended past k6's own default to include p99 (D84) — see search-read.js's
// own comment for why.

import http from 'k6/http';
import { check } from 'k6';

const BASE_URL = 'http://localhost:4001/v1';
const LOAD_USER_EMAIL = __ENV.LOAD_USER_EMAIL || 'load@example.com';
const LOAD_USER_PW = __ENV.LOAD_USER_PW || 'load-pw-123';
const BODY = JSON.stringify({ subject: 'load test ticket', description: 'generated by the M48 ticket-write rung' });

export const options = {
  scenarios: {
    ticket_write: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [{ duration: '20s', target: 60 }],
      gracefulStop: '0s',
    },
  },
  summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],
};

function login() {
  const res = http.post(`${BASE_URL}/auth/login`, JSON.stringify({ email: LOAD_USER_EMAIL, password: LOAD_USER_PW }), {
    headers: { 'Content-Type': 'application/json' },
    tags: { name: 'login' },
  });
  if (res.status !== 200) throw new Error(`login failed: ${res.status} ${res.body}`);
  return res.json('accessToken');
}

let token;

function authedRequest(method, url, body, tags) {
  if (!token) token = login();
  const attempt = () => {
    const headers = { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` };
    return method === 'GET' ? http.get(url, { headers, tags }) : http.post(url, body, { headers, tags });
  };
  let res = attempt();
  if (res.status === 401) {
    token = login();
    res = attempt();
  }
  return res;
}

export default function () {
  const res = authedRequest('POST', `${BASE_URL}/tickets`, BODY, { name: 'ticket-create' });
  check(res, { '201': (r) => r.status === 201 });
}
